import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { LOCKFILE_MANAGERS, RUN_PREFIX } from "./git-hooks.constants";
import type { PackageJson, PackageManager } from "./git-hooks.types";

export function detectPackageManager(projectPath: string): PackageManager {
  for (const { file, manager } of LOCKFILE_MANAGERS) {
    if (existsSync(path.join(projectPath, file))) return manager;
  }
  return "npm";
}

export function readPackageJson(projectPath: string): PackageJson {
  const packageJsonPath = path.join(projectPath, "package.json");
  const content = readFileSync(packageJsonPath, "utf-8");
  return JSON.parse(content);
}

export function isTypeScriptProject(
  projectPath: string,
  pkg: PackageJson,
): boolean {
  if (existsSync(path.join(projectPath, "tsconfig.json"))) return true;
  return Boolean(
    pkg.dependencies?.["typescript"] || pkg.devDependencies?.["typescript"],
  );
}

function checkBlock(
  manager: PackageManager,
  script: string,
  label: string,
): string {
  return `echo "▶ ${label}"\n${RUN_PREFIX[manager]} ${script}\n\n`;
}

// Every @tertium TypeScript project is expected to carry standard "lint" and "typecheck"
// scripts (same convention enforced by scripts/npm-publish-workflow), so for TS projects these
// checks are always included even if the scripts aren't defined yet - the hook then fails
// loudly with "missing script" instead of silently skipping the check. "test" only runs if
// the project actually defines it, since not every project has a test suite.
export function buildPreCommitHook(
  pkg: PackageJson,
  manager: PackageManager,
  isTypeScript: boolean,
): string {
  const checks = [
    isTypeScript || pkg.scripts?.["lint"]
      ? checkBlock(manager, "lint", "Lint")
      : "",
    isTypeScript || pkg.scripts?.["typecheck"]
      ? checkBlock(manager, "typecheck", "Typecheck")
      : "",
    pkg.scripts?.["test"] ? checkBlock(manager, "test", "Test") : "",
  ].join("");

  return `#!/usr/bin/env sh
# Generated by @tertium/js scripts/git-hooks - runs on every commit via core.hooksPath
set -e

${checks}`;
}
