import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import {
  INSTALL_COMMAND,
  LOCKFILE_MANAGERS,
  RUN_PREFIX,
  TOOLCHAIN_SETUP_STEP,
} from "./npm-publish-workflow.constants";
import type { PackageJson, PackageManager } from "./npm-publish-workflow.types";

export function detectPackageManager(projectPath: string): PackageManager {
  for (const { file, manager } of LOCKFILE_MANAGERS) {
    if (existsSync(path.join(projectPath, file))) return manager;
  }
  return "npm";
}

export function readPackageJson(projectPath: string): PackageJson {
  const packageJsonPath = path.join(projectPath, "package.json");
  const content = readFileSync(packageJsonPath, "utf-8");
  return JSON.parse(content);
}

export function isTypeScriptProject(
  projectPath: string,
  pkg: PackageJson,
): boolean {
  if (existsSync(path.join(projectPath, "tsconfig.json"))) return true;
  return Boolean(
    pkg.dependencies?.["typescript"] || pkg.devDependencies?.["typescript"],
  );
}

export function stepLine(
  manager: PackageManager,
  script: string,
  name: string,
): string {
  return `      - name: ${name}\n        run: ${RUN_PREFIX[manager]} ${script}\n\n`;
}

export function buildStep(
  manager: PackageManager,
  pkg: PackageJson,
  script: string,
  name: string,
): string {
  if (!pkg.scripts?.[script]) return "";
  return stepLine(manager, script, name);
}

export function buildWorkflowYaml(
  pkg: PackageJson,
  manager: PackageManager,
  isTypeScript: boolean,
): string {
  // Every @tertium TypeScript project is expected to carry standard "lint" (biome check)
  // and "typecheck" (tsc --noEmit) scripts, so for TS projects these steps are always
  // emitted - a missing script fails CI loudly rather than silently skipping the check.
  // Non-TS projects fall back to detecting whatever scripts actually exist (and skip
  // typecheck entirely, since tsc doesn't apply).
  const lintStep = isTypeScript
    ? stepLine(manager, "lint", "Lint")
    : buildStep(manager, pkg, "lint", "Lint");
  const typecheckStep = isTypeScript
    ? stepLine(manager, "typecheck", "Typecheck")
    : "";
  const buildStepYaml = buildStep(manager, pkg, "build", "Build");
  const testStep = buildStep(manager, pkg, "test", "Test");

  return `# Generated by @tertium/js scripts/npm-publish-workflow - https://docs.npmjs.com/trusted-publishers
name: Publish to npm

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"

${TOOLCHAIN_SETUP_STEP[manager]}      - name: Install dependencies
        run: ${INSTALL_COMMAND[manager]}

${lintStep}${typecheckStep}${buildStepYaml}${testStep}      - name: Publish
        run: npm publish
`;
}
